### PR TITLE
Resolve bugs

### LINKED ISSUE #31: Fix: List style scroll and sort
As part of feature, it has to considering the following specs
- [x]  Add scroll style
- [x] Sort desc date
- [x] Show in a single size the contents of the list

### PR DESCRIPTION
**Pull request by paulotijero**
Resolve #31

### CODE REVIEW

File: controller/list_methods.rb [hunk 1]
```diff
@@ -5,35 +5,37 @@ def list_daily
...
+    if val[1]["is_deleted"] == 0
       list.push(val[1])
     end
   end
-  list.sort_by{|value| value["datetime"].to_i}
-  list.each do |val|
-    val["datetime"] = DateTime.parse(val["datetime"]).strftime("%d-%m-%Y %H:%M:%S")
-  end
-  list
+  list = sort_parse(list)
```
Comment (MariethPerez) [inline controller/list_methods.rb]: @paulotijero Please Can you explain me Why do you use "sort_parse"?

Comment (paulotijero) [reply controller/list_methods.rb]: "sort_parse" is a function that parse and order

File: views/list_entry.erb [hunk 2]
```diff
@@ -1,92 +1,89 @@
...
-        <div class="card-list">
-          <a href="/add-entry">
-            <button type="button" class="btn btn-default btn-sm" title="Agregar">
-              <span
-                    class="glyphicon glyphicon-plus-sign"
-                    aria-hidden="true"
-              ></span>
-            </button>
-          </a>
+  <div class="scrollbar style-scroll">
```
Comment (liannivin) [inline views/list_entry.erb]: Excellent improve for our project!
